In [29]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta

fake = Faker("en_IN")

random.seed(42)
np.random.seed(42)

In [30]:
NUM_CUSTOMERS = 30000

In [31]:
locations = {
    "Delhi":"Delhi",
    "Noida":"Uttar Pradesh",
    "Ghaziabad":"Uttar Pradesh",
    "Gurugram":"Haryana",
    "Faridabad":"Haryana"
}

In [32]:
occupation_income = {

    "Student":(0,300000),

    "Teacher":(350000,800000),

    "Engineer":(600000,2000000),

    "Doctor":(1000000,4000000),

    "Business":(800000,5000000),

    "Government Employee":(500000,1500000),

    "Lawyer":(700000,2500000),

    "Manager":(800000,3000000)

}

In [33]:
customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    city = random.choice(list(locations.keys()))

    state = locations[city]

    occupation = random.choice(list(occupation_income.keys()))

    income = random.randint(
        occupation_income[occupation][0],
        occupation_income[occupation][1]
    )

    gender = random.choice(["Male","Female"])

    status = random.choices(
        ["Active","Inactive"],
        weights=[95,5]
    )[0]

    customers.append({

        "CustomerID": i,

        "FirstName": fake.first_name(),

        "LastName": fake.last_name(),

        "Gender": gender,

        "DOB": fake.date_of_birth(
            minimum_age=18,
            maximum_age=70
        ),

        "Phone": fake.phone_number(),

        "Email": fake.email(),

        "City": city,

        "State": state,

        "Occupation": occupation,

        "AnnualIncome": income,

        "JoinDate": fake.date_between(
            start_date="-10y",
            end_date="today"
        ),

        "CustomerStatus": status

    })

In [19]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,CustomerID,FirstName,LastName,DOB,Phone,Email,City,State,JoinDate
0,1,Indira,Ravel,1958-02-22,+915769645046,bhatnagarjackson@example.net,Bally,Haryana,2021-07-08
1,2,Neel,Kale,1996-03-23,4749142794,merchantzinal@example.org,Chandrapur,Jharkhand,2025-09-07
2,3,Edhitha,Chauhan,1994-04-17,06067826457,divya60@example.org,Katihar,Meghalaya,2023-02-25
3,4,Reva,Wadhwa,1962-07-12,7354429932,kdani@example.org,Tiruchirappalli,Odisha,2019-07-01
4,5,Onkar,Ramachandran,1955-12-13,01352872984,harini12@example.org,Surat,Goa,2022-08-17

In [34]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,CustomerID,FirstName,LastName,Gender,DOB,Phone,Email,City,State,Occupation,AnnualIncome,JoinDate,CustomerStatus
0,1,Vihaan,Sharma,Male,1980-06-16,+919300183689,ssoman@example.com,Delhi,Delhi,Student,144194,2023-01-31,Active
1,2,Upasna,Minhas,Female,2001-11-08,03413817142,bnaidu@example.net,Delhi,Delhi,Teacher,659588,2021-05-02,Active
2,3,Radha,Sama,Male,1974-03-11,3899680900,harini09@example.org,Delhi,Delhi,Doctor,1975850,2018-09-07,Active
3,4,Anita,Chhabra,Female,1961-01-16,09974180003,siyasrinivas@example.net,Faridabad,Haryana,Lawyer,1162297,2024-05-16,Active
4,5,Ojas,Muni,Female,1972-11-08,+918245239454,veer44@example.net,Delhi,Delhi,Engineer,1486286,2026-07-10,Active

In [35]:
customers_df.to_csv("customers.csv",index=False)

print("Customers Generated Successfully")

Customers Generated Successfully